### ISSUE TITLE
Adding some features on a player's page

### ISSUE THREAD

**Issue by neverperfect** [datdota/datdota#10]
A quick suggestion on adding which team a player played in during each league/matches, in his lifetime history of matches, for a time-series predicting purpose, just to see how a player synergize with each team he was in.

Also on a specific player's page for the "Recent Games" it only shows latest 100 matches?
Would it be possible for us to toggle between recent games and/or his lifetime matches.

Thanks in advance

**Comment by Noxville** [comment]
1. What do you mean by 'synergize' with team? I intend to put some of the significant squads the player was in for each team (as in, groups of 5 players).

2. It could show more than 100 matches (perhaps all), it's just a question of data time loading. I dislike the Ajax-heavy tables, so loading a player's page with 1.5k games would take some more time.

**Comment by neverperfect** [comment]
Regarding point 1, the synergize is the project I'm working on.. haha
I guess the "squad" feature would work better rather than "team", thanks for the idea..

Other than that, it would still be awesome if there's a feature to show which team a player was in on every single of his matches, just to recap data of a player's team history in a time-series format..

**Comment by Noxville** [comment]
Might prefer the full-matches to be put into the API then, and just leave 'recent matches' to be the last 100.

**Comment by Noxville** [comment]
Think this is mostly solved by the new player page, and squad features? If not - just open it again.
