### ISSUE TITLE
Inclusive inconsistency

### ISSUE THREAD

**Issue by gravitos** [datdota/datdota#13]
If i search for a Match and put in f.e. after 27th May it finds matches that were played on the 27th. But if I search for a match and put in before 27th May it won't find matches that were played on the 27th.

**Comment by Noxville** [comment]
Cool - changed it to be <= {end date @ 23:59:59}

Just note that it's based on UTC time. Re-open if you find any more bugs related to this (it seems right on the few examples I looked at).
