### ISSUE TITLE
Add team elo to endpoint

### ISSUE THREAD

**Issue by Sycopquaehantastui** [datdota/datdota#18]
"Every team has an Elo32, Elo64, Glicko and Glicko 2 rating
for a team to be shown on the ratings page, the team must have a Glicko 2 Phi value (RD equivalent for Glicko 1) below 70.0 to be shown.
if they are below that threshold on Glicko 2, then all their ratings are shown"

Would be great if ratings could be accessed for all teams with an api endpoint

**Comment by Sneg42** [comment]
That's great idea. And very useful.
