### ISSUE TITLE
Date sorting for Match finder

### ISSUE THREAD

**Issue by trevize23** [datdota/datdota#24]
Issue: Sorting by date will result in sorting of the first parameter only (days)
Where: http://www.datdota.com/matchfinder/classic?default=true
Example: Alliance vs Natus Vincere (with all patches selected)

**Comment by Noxville** [comment]
I could fix this by writing a custom DataTable Sortable/Comparator, but in this case I don't think I will since you can easily just sort by match_id. (Re-open this issue if you think there's other places where it needs to be fixed).
