### ISSUE TITLE
Incorrect match times

### ISSUE THREAD

**Issue by ThePianoDentist** [datdota/datdota#25]
Using `https://www.datdota.com/splits/43`,
it seems that a lot of the date-times of the games are off, sometimes by ~12hours.
i.e. https://www.datdota.com/matches/262322091

looking at the match times of all games in ti3, the max seems to be 12:XX,
so likely there is a date-formatting issue, confusing 12hr/24hr clock somewhere

edit: the 12hr times are in csv/downloaded files as well, so not frontend

**Comment by Noxville** [comment]
Replaced all with the 24 hour format.
