### ISSUE TITLE
Display issue in team page

### ISSUE THREAD

**Issue by Serialloser** [datdota/datdota#3]
When browsing a team page like this one [http://www.datdota.com/teams/2586976]( http://www.datdota.com/teams/2586976) I have a display issue.

![teamdisplayissue](https://cloud.githubusercontent.com/assets/1119442/24564132/d6bc09be-161e-11e7-8451-38633719c7ac.png)

Browser used : Chrome in private mode to disable any extension who could mess with the page except uBlock Origin.

**Comment by Noxville** [comment]
Looks like it's too narrow. I'll see if perhaps making it 6/6 column layout (instead of 8/4) makes it any better.

**Comment by Serialloser** [comment]
Well to complete this report. This behavior is not limited to the team page, it happens in all pages where you are using a search if the column is too small like this one too [ http://www.datdota.com/heroes/performances?default=true](http://www.datdota.com/heroes/performances?default=true)

**Comment by Noxville** [comment]
I'm just going to disable the "Show <X> entries". If you delete those entities in your web browser, does the layout look okay?

**Comment by Serialloser** [comment]
No the search label still doesn't fit next to the input box

**Comment by invokr** [comment]
Minimum res for it to not leak into the second row is 2200px+ width.
I blame the uhd dell monitors at work @Noxville

**Comment by Serialloser** [comment]
Probably, I'm using a 1080p monitor

**Comment by Noxville** [comment]
Perhaps have a look now, I redid the default styling on all the tables that could scroll - let me know what you think.

**Comment by Noxville** [comment]
![selection_090](https://user-images.githubusercontent.com/204781/37236490-8ab82e3c-2408-11e8-9ae8-8508bc010916.png)

Also horizontal scrolling working ^
