### ISSUE TITLE
Match finder problem

### ISSUE THREAD

**Issue by ENegatiVY** [datdota/datdota#33]
On the page https://www.datdota.com/matchfinder/classic

I want to search games in a league or with a certain patch.

But if I don't select a team, it always returns no result.

for example this link works,https://www.datdota.com/matchfinder/classic?team-a=726228&patch=7.23&after=10%2F03%2F2010&before=07%2F12%2F2019&duration=0%3B200&duration-value-from=0&duration-value-to=200&tier=1&tier=2&valve-event=does-not-matter&threshold=1

but if I remove the team,it wont work,like this. https://www.datdota.com/matchfinder/classic?patch=7.23&after=10%2F03%2F2010&before=07%2F12%2F2019&duration=0%3B200&duration-value-from=0&duration-value-to=200&tier=1&tier=2&valve-event=does-not-matter&threshold=1

**Comment by Noxville** [comment]
This page isn't designed for that kind of searching - it's designed for some combination of heroes and/or teams which are known, otherwise there's almost always too many matches for a patch.
