### ISSUE TITLE
What does Elo Shift and Elo Games mean?

### ISSUE THREAD

**Issue by XinpengLiu321** [datdota/datdota#34]
Hi, when I browsing the datdota website I found that, at the "Heros/Performances by Elo" page, There are columns named "avg. Elo Shift" and "#Elo Games". Can somebody explain how those two columns was calculated and what do those numbers imply?
I found somthing about  Elo rating system on wikipedia. Does those two columns related to the Elo rating system?
Thanks a lot!

**Comment by Noxville** [comment]
What's wrong with a raw winrate? Well - it would be totally accurate if all teams were similarly skilled. Unfortunately that's not the case - teams play against very different skilled opponents, and in different compositions. For example most teams losing to Secret is an expected result, but beating Secret as a tier 3 team is a very unexpected result. This is where rating systems like the Elo rating system came from: you get points for winning and you lose points for losing - but the points exchanged are proportional to how expected or unexpected the result was.

The Elo Shift approach is basically a potential solution to the winrate problem. Basically we use a modification use the Elo shift in a match for the heroes on each side (+ for winners / - for losers). Averaging this out over a large number of games on a per-hero basis gives the average Elo gain or loss in matches for the team with this hero - representing the "performance" of the hero. You can convert this shift into a win rate % shift easily, but it's nicer to work with as a raw number.

Elo updates only happen once a day (we recalculate all the Elo points for all matches using k=32 and k=64), and if there are live games as the update tries to happen it can fail. The # Elo games is shown here as a column so you know the sample size of the matches with Elo values set (whereas the winrate is based on the win-loss sample).

**Comment by XinpengLiu321** [comment]
So，for example,  Ember Spirit&Grimstroke have a Elo Shift of 10.674, meaning that when those two heros are on the same side they will get  10.674% more chance (60.674%) to win the battle, and the result is modified by the relative strength of teams in the 31 matches. Am I understanding it correctly?

**Comment by Noxville** [comment]
The range of Elo shift used is (-64.0 to +64.0) since it's using Elo64, so you need to normalize and linearly shift that value first. The range is (64 - (-64) = 128, with a mean of 0.0. 

As a result, your effective winrate shift becomes:

+10.674/128 = +8.34%

So the effective winrate is 50% + 8.34% = 58.34%.

**Comment by XinpengLiu321** [comment]
Thank you very much!

**Comment by XinpengLiu321** [comment]
Another question: In which case the Elo32 was used and in which case the Elo64 was used?

**Comment by Noxville** [comment]
All calculations involving Elo Shift are using Elo (k=64). k=32 is a slightly better single-match predictor for team-vs-team (when looking at a large competitive sample) but can be a bit slow to adapt to changes. Since you're looking at aggregate metrics over a significant sample, k=64 has had better performance.
