### ISSUE TITLE
Timeout error for match duration

### ISSUE THREAD

**Issue by Tasty213** [datdota/datdota#35]
Hi,
If you go onto datdota and select matches->duration (http://www.datdota.com/match-durations?default=true)  then you get an Cloudflare error page.

**Comment by Noxville** [comment]
Once every ~10-12 days the database indexes basically get so screwed up I take the site down for 15 mins, reindex them, and then put the site up. If basic functionality on the site (like this page) are slow, just poke me on Discord or Twitter and I'll reindex.

**Comment by Tasty213** [comment]
Could a Cron job be added for re indexing, just to save you the bother
if nothing else?

**Comment by Noxville** [comment]
Depends more on usage and long-running big queries - especially when I reparse a few thousand games to extract some more data (so I don't want to shut down mid-parse).
