### ISSUE TITLE
empty column/missing leagueid in leagues csv output

### ISSUE THREAD

**Issue by howardchung** [datdota/datdota#4]
On http://www.datdota.com/leagues

The CSV download option on the leagues page returns a CSV file with an empty first column.

On the table this is the image column, but in the CSV it should probably be the leagueid

**Comment by howardchung** [comment]
If the CSV is generated from the table state, then the simplest fix is probably just to add another column with the leagueid and let the user ignore the empty column.

**Comment by Noxville** [comment]
Fixed

DataTables are quite cool - but sometimes inflexible. The easiest thing is just to make a span with display:none with text inside to populate CSV/PDF cells.
