### ISSUE TITLE
 Claro gaming Apu League Series

### ISSUE THREAD

**Issue by RefreshJunior** [datdota/datdota#40]
Good afternoon, I would like to have access to the data of the
"Claro gaming Apu League Series", however I think the tournament is marked as amateur.

Is there any way to have these accesses?

**Comment by Noxville** [comment]
It should've been marked as semi-pro, just updated it now and parsing should like 15-20 mins for the matches.

**Comment by RefreshJunior** [comment]
TY master! 

I take the opportunity to ask, do you teach a course on the Dota API?
