### ISSUE TITLE
DPC 2021-2022 Tour 2 Qualifiers (SA) - Presented by 4D Esports

### ISSUE THREAD

**Issue by RefreshJunior** [datdota/datdota#43]
good night. I am not able to filter open qualifiers for tour 2 of DPC SA. Is the championship marked as amateur?

**Comment by Noxville** [comment]
All open qualifiers are marked as amateur.

**Comment by RefreshJunior** [comment]
Is there any way to consult the Open through datdota? Or can you mark them as semi pro?

**Comment by RefreshJunior** [comment]
The Winter Tour Open information can be consulted, for example
