### ISSUE TITLE
https://abilitydraft.datdota.com/heroes Bug

### ISSUE THREAD

**Issue by Bratish971** [datdota/datdota#47]
https://abilitydraft.datdota.com/heroes/84
https://abilitydraft.datdota.com/heroes/68
https://abilitydraft.datdota.com/heroes/74
https://abilitydraft.datdota.com/heroes/82
https://abilitydraft.datdota.com/heroes/86
https://abilitydraft.datdota.com/heroes/113
https://abilitydraft.datdota.com/heroes/10

All these pages just dead with "An error has occurred"

**Comment by Noxville** [comment]
These are all rare heroes (no ultimate, so they appear less commonly), which I assumed had some bug because of the no-ultimate part. Turns out they just appear less frequently, so they haven't necessarily played with every ability - and that was breaking stuff.

Should be fixed now.
