### ISSUE TITLE
EPL World Series: América Temporada 2022-2023

### ISSUE THREAD

**Issue by RefreshJunior** [datdota/datdota#52]
Hey Noxville, 

EPL World Series data is not available on datdota. Is it possible to have access to the data of this league?

TY sensei

**Comment by Noxville** [comment]
I've added both the EPL leagues as tier 3:

* EPL World Series: America 2022-2023 Season (14783) ~ 103 matches
* EPL World Series: America (14679) ~ 71 matches

They're parsing now.

**Comment by RefreshJunior** [comment]
Thank you very much!
