### ISSUE TITLE
Yatoro's most kills record is wrong

### ISSUE THREAD

**Issue by x42bn6** [datdota/datdota#53]
Yatoro had a game where he had 30 kills: https://www.datdota.com/matches/7101136299

However, on the Players > Records screen (https://www.datdota.com/players/records?default=true) and Players > Single Performances screen (https://www.datdota.com/players/single-performance?players=321580662&patch=7.33&after=01%2F01%2F2010&before=22%2F06%2F2023&duration=0%3B200&duration-value-from=0&duration-value-to=200&tier=1&tier=2&valve-event=does-not-matter), his record number of kills is 23.

**Comment by Noxville** [comment]
You've got records on default=true, which you can see in the filter panel filters on the current patch only.

DLS19 was 7.32

**Comment by x42bn6** [comment]
Ah, I'm an idiot.  I would have thought that "records" would have automatically defaulted to all patches, though, although maybe this might be a bit taxing as a default.
