### ISSUE TITLE
linked pages do not rehydrate form state

### ISSUE THREAD

**Issue by howardchung** [datdota/datdota#7]
Seems to be an issue on the API-populated fields such as team and league.

Example:
http://datdota.com/drafts?faction=both&first-pick=either&teams=111474&tier=1&tier=2&valve-event=does-not-matter&patch=7.04&patch=7.03&patch=7.02&patch=7.01&patch=7.00&patch=6.88&patch=6.87&patch=6.86&patch=6.85&patch=6.84&patch=6.83&patch=6.82&patch=6.81&patch=6.80&patch=6.79&patch=6.78&patch=6.77&patch=6.76&patch=6.75&patch=6.74&winner=either&after=01%2F01%2F2011&before=02%2F04%2F2017&duration=0%3B200

Expected behavior:
The teams selector should repopulate itself with the selected team (Alliance, 111474)

**Comment by Noxville** [comment]
Fixed

(http://datdota.com/drafts?faction=both&first-pick=either&teams=111474&leagues=5197&tier=1&tier=2&valve-event=does-not-matter&patch=7.05&patch=7.04&patch=7.03&patch=7.02&patch=7.01&patch=7.00&patch=6.88&patch=6.87&patch=6.86&patch=6.85&patch=6.84&patch=6.83&patch=6.82&patch=6.81&patch=6.80&patch=6.79&patch=6.78&patch=6.77&patch=6.76&patch=6.75&patch=6.74&winner=either&after=01%2F01%2F2011&before=02%2F04%2F2017&duration=0%3B200)
