### ISSUE TITLE
Display Issue for Match Filters Section

### ISSUE THREAD

**Issue by mikemcgo** [datdota/datdota#8]
This issue appears when the width of the browser window decreases. Text in the patch section moves under the patch list, as well as the Winner selector's titles move to a confusing orientation.

![match filters display](https://cloud.githubusercontent.com/assets/6385433/24583221/3f26d0a4-1711-11e7-973c-1c16b6446cac.PNG)

Browser - Chrome, issue appears at dimension 992x894 to 1412x894.

**Comment by davidfischer** [comment]
I created a gist with a proposed change for this: https://gist.github.com/davidfischer/3c5d679fe106a1d0d13d84c49221384a

In general, I think the best fix is for the filters to take up a larger amount screen real estate. This will definitely look better at the dimensions @mikemcgo is using. It looks perhaps slightly more awkward at really large resolutions (>1920px wide) but is still completely usable.

**Comment by Noxville** [comment]
Roger that - added it in. Thanks @davidfischer .
