### ISSUE TITLE
Unknown image link

### ISSUE THREAD

**Issue by Serialloser** [datdota/datdota#9]
I wanted to see the most picked/banned hero for DAC and ended up here [http://www.datdota.com/drafts?faction=both&first-pick=either&leagues=5197&valve-event=does-not-matter&patch=7.04&winner=either&after=01%2F01%2F2011&before=03%2F04%2F2017&duration=0%3B200](http://www.datdota.com/drafts?faction=both&first-pick=either&leagues=5197&valve-event=does-not-matter&patch=7.04&winner=either&after=01%2F01%2F2011&before=03%2F04%2F2017&duration=0%3B200)

At the bottom of the page there's a list of unpicked / unbanned heroes, in that list there's a link to an unknown image.

![unknown](https://cloud.githubusercontent.com/assets/1119442/24611370/deea447e-184f-11e7-939a-784e383f06da.png)

**Comment by Noxville** [comment]
Fixed.
